=== vaszil1337/XGBT95WebXML/XGBT95_0924/XGBT95_orarend.dtd
<!ELEMENT XGBT95_orarend (ora*)>
<!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
<!ATTLIST ora
    id      ID      #REQUIRED
    tipus   (elmÃ©let|gyakorlat) #REQUIRED
>
<!ELEMENT targy (#PCDATA)>
<!ELEMENT idopont (nap, tol, ig)>
<!ELEMENT nap (#PCDATA)>
<!ELEMENT tol (#PCDATA)>
<!ELEMENT ig (#PCDATA)>
<!ELEMENT helyszin (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT szak (#PCDATA)>

=== vaszil1337/XGBT95WebXML/XGBT95_0924/XGBT95_orarend_kulso.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE XGBT95_orarend SYSTEM "XGBT95_orarend.dtd">
<XGBT95_orarend>
    <ora id="h1" tipus="elmélet">
        <targy>Elektrotechnika-elektronika</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>8:00</tol>
            <ig>9:30</ig>
        </idopont>
        <helyszin>E/3</helyszin>
        <oktato>Szabó Norbert István</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h2" tipus="elmélet">
        <targy>Web technológiák 1</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>10:00</tol>
            <ig>11:30</ig>
        </idopont>
        <helyszin>E/5</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h3" tipus="gyakorlat">
        <targy>Angol műszaki szaknyelv 1</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>12:00</tol>
            <ig>13:30</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dobronyi Eszter</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h4" tipus="gyakorlat">
        <targy>Web technológiák 1</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>14:00</tol>
            <ig>15:30</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h5" tipus="elmélet">
        <targy>Mobil programozási alapok</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>16:00</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h6" tipus="gyakorlat">
        <targy>Mobil programozási alapok</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>18:00</tol>
            <ig>19:30</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>

    <ora id="h7" tipus="elmélet">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>10:00</tol>
            <ig>11:30</ig>
        </idopont>
        <helyszin>E/32</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h8" tipus="elmélet">
        <targy>Valószínűségszámítás és matematikai statisztika</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>14:00</tol>
            <ig>15:30</ig>
        </idopont>
        <helyszin>T050</helyszin>
        <oktato>Dr. Glavositcs Tamás</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h9" tipus="gyakorlat">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>12:00</tol>
            <ig>13:30</ig>
        </idopont>
        <helyszin>E/32</helyszin>
        <oktato>Fazekas Levente Áron</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h10" tipus="gyakorlat">
        <targy>Elektrotechnika-elektronika</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>14:00</tol>
            <ig>15:30</ig>
        </idopont>
        <helyszin>A3/313</helyszin>
        <oktato>Dr. Kozsely Gábor</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h11" tipus="gyakorlat">
        <targy>UNIX rendszergazda</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>17:00</tol>
            <ig>18:30</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Baksa Attila</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>

    <ora id="h12" tipus="elmélet">
        <targy>UNIX rendszergazda</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>8:00</tol>
            <ig>9:30</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Baksa Attila</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h13" tipus="elmélet">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>8:00</tol>
            <ig>9:30</ig>
        </idopont>
        <helyszin>T050</helyszin>
        <oktato>Dr. Kovács László József</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h14" tipus="gyakorlat">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>10:00</tol>
            <ig>11:30</ig>
        </idopont>
        <helyszin>L103</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
    <ora id="h15" tipus="gyakorlat">
        <targy>Valószínűségszámítás és matematikai statisztika</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>14:00</tol>
            <ig>15:30</ig>
        </idopont>
        <helyszin>T050</helyszin>
        <oktato>Dr. Nagy Noémi</oktato>
        <szak>mérnökinformatikus</szak>
    </ora>
</XGBT95_orarend>
